### ISSUE TITLE
LICENSE for 0.1.0

### ISSUE THREAD

**Issue by Silviu-Caprar** [arcticicestudio/nord-highlightjs#12]
Hi there,

Can you please specify which license apply on version 0.1.0 ? 

Is it Apache License 2.0 or MIT License ? Cause Apache License 2.0 is listed although at the top MIT is mentioned.

Thank you

**Comment by arcticicestudio** [comment]
Hi @Silviu-Caprar, this repository migrated to the MIT license in #7, but since then no new version has been released. If you take it exactly, version 0.1.0 is still licensed through Apache, but as of 09e02c87b89a8664d8388194623daf2800489b25 the code is licensed under MIT. If you're using the latest commit from the `develop` branch you're good to go to use the code with the MIT license applied on it.
